name: film_flu
description: A project of movies and something more
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.1.0+15

environment:
  sdk: '^3.5.4'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  horusvision: ^0.1.1

  
  go_router: ^14.4.1


  # Freezed - Model Smart Generation
  #
  # Annotations of Freezed package
  # https://pub.dev/packages/freezed_annotation
  freezed_annotation: ^2.4.1

  # Json - Json Model Smart Generation
  #
  # Annotations to help freezed generate remote data-models classes
  # https://pub.dev/packages/json_annotation
  json_annotation: ^4.9.0

  dio: ^5.0.0

  retrofit: ^4.1.0
  envied_generator: ^0.5.3
  
  intl: ^0.19.0
  get_it: ^7.2.0
  lottie: ^3.1.2
  envied: ^0.5.3
  http: ^1.2.2
  package_info_plus: ^4.2.0
  flutter_svg: ^2.0.7
  auto_size_text: ^3.0.0
  material_symbols_icons: ^4.2668.0
  shared_preferences: ^2.0.13
  youtube_player_iframe: ^5.1.3
  url_launcher: ^6.1.11
  cached_network_image: ^3.3.1
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  pretty_dio_logger: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.11
  json_serializable: ^6.8.0

  # Testing
  #
  # A mock framework inspired by Mockito
  # https://pub.dev/packages/mockito
  mockito: ^5.4.4

  flutter_launcher_icons: ^0.14.1
  test: ^1.25.2
  riverpod_generator: ^2.6.2
  custom_lint: ^0.7.0
  riverpod_lint: ^2.6.2
  freezed: ^2.5.7

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/flags/
    - assets/animations/
    - fonts/
  fonts:
    - family: YsabeauInfant
      fonts:
        - asset: fonts/YsabeauInfant-Regular.ttf
    - family: LilitaOne
      fonts:
        - asset: fonts/LilitaOne-Regular.ttf
    - family: ShadowsIntoLight
      fonts:
        - asset: fonts/ShadowsIntoLight-Regular.ttf

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/images/logo.png"
  min_sdk_android: 21
  adaptive_icon_background: "#000"
  web:
    generate: true
    image_path: "assets/images/logo.png"
    background_color: "#000"
    theme_color: "#D42029"

flutter_intl:
  enabled: true
  class_name: AppLocalizations