name: film_flu
description: A project of movies and something more
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 2.0.3+18

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  ## Navigation:
  go_router: ^15.1.2 # A declarative routing package for Flutter.

  ## Data Modeling:
  freezed_annotation: ^2.4.1 # Annotations for the `freezed` package, enabling immutable data class generation.
  json_annotation: ^4.9.0 # Annotations for the `json_serializable` package, used to generate JSON serialization code.


  ## Core Functionality:
  dio: ^5.8.0+1 # A powerful HTTP client for Flutter, supporting interceptors, transformers, and more. Ideal for API interactions.
  http: ^1.3.0 # A foundational HTTP client library for making web requests in Flutter.
  pretty_dio_logger: ^1.4.0 # An elegant and informative logger for Dio, making API debugging much easier.
  url_launcher: ^6.1.11 # A package to launch URLs, phone calls, SMS, and emails from your Flutter app.

  ## State Management & Dependency Injection:
  flutter_riverpod: ^2.5.1 # A reactive state management solution for Flutter, providing a simple and powerful way to manage application state.
  riverpod_annotation: ^2.6.1 # Codegen support for Riverpod, simplifying the creation of providers and reducing boilerplate.

  ## Asynchronous Operations & Data Handling:
  cached_network_image: ^3.4.1 # A package to display images fetched from the network with built-in caching capabilities, improving performance and reducing bandwidth usage.

  ## UI Enhancements & Styling:
  lottie: ^3.3.1 # Render beautiful vector-based animations in your Flutter app using Lottie files (JSON-based animation format).
  flutter_svg: ^2.0.17 # A package to render Scalable Vector Graphics (SVG) in Flutter, ensuring crisp visuals across different screen sizes.
  auto_size_text: ^3.0.0 # Automatically resizes text to fit within its bounds, ensuring readability across various screen sizes and text lengths.
  material_symbols_icons: ^4.2811.0 # Provides access to the extensive Material Symbols icon set from Google.
  shimmer: ^3.0.0 # Adds shimmering effect to widgets, often used as a visual placeholder during loading states.
  flutter_widget_from_html: ^0.16.0 # Renders HTML content as Flutter widgets, useful for displaying formatted text or simple web content.

  ## Utility & Platform Services:
  intl: ^0.20.2 # Provides internationalization and localization facilities, crucial for supporting multiple languages.
  package_info_plus: ^8.3.0 # Retrieves information about the application package, such as app name, version, and build number.
  shared_preferences: ^2.5.2 # Provides a simple way to store and retrieve key-value pairs of primitive data types persistently across app launches.
  path_provider: ^2.1.5 # Provides access to commonly used locations on the device's file system, such as temporary and application support directories.

  ## Environment Variables & Configuration:
  envied: ^1.1.1 # A package for managing environment variables in Flutter apps securely.
  envied_generator: ^1.1.1 # Code generator for the `envied` package, simplifying the access to environment variables.

  ## Multimedia:
  youtube_player_iframe: ^5.2.1 # Embed and control YouTube videos within your Flutter app using an iframe-based player.

  ## Firebase Integration:
  firebase_analytics: ^11.4.4 # Integrates with Firebase Analytics to track user behavior and gain insights into app usage.
  firebase_core: ^3.3.0 # The core Firebase plugin for Flutter, necessary for initializing other Firebase services.
  firebase_auth: ^5.5.1 # Provides Firebase Authentication services for user sign-in and management.

  ## Accessibility & Feedback:
  color_blindness: ^0.2.0 # Tools and widgets to simulate different types of color blindness, aiding in accessibility testing.
  feedback: ^3.1.0 # A package to easily implement in-app feedback mechanisms.
  flutter_email_sender: ^7.0.0 # Allows your Flutter app to compose and send emails.
  rive: ^0.13.20
  # horusvision:
  #   path: ../horusvision/

dev_dependencies:
  flutter_test:
    sdk: flutter

  ## Linter & Code Analysis:
  flutter_lints: ^6.0.0 # A set of recommended lints to enforce good coding practices in Flutter.

  ## Code Generation:
  build_runner: ^2.4.15 # A generic package for running code generators in Flutter.
  json_serializable: ^6.9.4 # Automatically generates code for serializing to and from JSON.
  riverpod_generator: ^2.6.4 # Codegen support for Riverpod, simplifying the creation of providers.
  freezed: ^2.5.8 # Immutable data classes with built-in support for equality, copying, and `toString`.
  go_router_builder: ^2.8.2 # Code builder for the `go_router` package, simplifying route definition.

  ## Testing:
  mockito: ^5.4.5 # A mock framework inspired by Mockito, useful for creating test doubles.
  test: ^1.25.15 # The core testing framework for Dart and Flutter.
  build_verify: ^3.1.0 # Ensures that generated files are up-to-date.

  ## Custom Linting:
  custom_lint: ^0.7.3 # A framework for creating custom lint rules for Flutter and Dart.
  riverpod_lint: ^2.6.4 # Custom lint rules specifically for Riverpod.

  ## App Configuration:
  flutter_launcher_icons: ^0.14.1 # A package to easily generate app launcher icons for different platforms.

dependency_overrides:
  analyzer_plugin: ^0.13.1


flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/flags/
    - assets/animations/
    - fonts/
  fonts:
    - family: YsabeauInfant
      fonts:
        - asset: fonts/YsabeauInfant-Regular.ttf
    - family: LilitaOne
      fonts:
        - asset: fonts/LilitaOne-Regular.ttf
    - family: ShadowsIntoLight
      fonts:
        - asset: fonts/ShadowsIntoLight-Regular.ttf

flutter_intl:
  enabled: true
  class_name: AppLocalizations