// Mocks generated by Mockito 5.4.4 from annotations
// in film_flu/test/features/person_detail/bloc/person_detail_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:film_flu/app/types/result.dart' as _i3;
import 'package:film_flu/domain/models/person_entity.dart' as _i7;
import 'package:film_flu/domain/repository_contracts/person_repository_contract.dart'
    as _i6;
import 'package:film_flu/presentation/features/person_details/bloc/person_details_bloc.dart'
    as _i2;
import 'package:flutter_bloc/flutter_bloc.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePersonDetailsState_0 extends _i1.SmartFake
    implements _i2.PersonDetailsState {
  _FakePersonDetailsState_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeResult_1<T> extends _i1.SmartFake implements _i3.Result<T> {
  _FakeResult_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [PersonDetailsBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockPersonDetailsBloc extends _i1.Mock implements _i2.PersonDetailsBloc {
  @override
  _i2.PersonDetailsState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakePersonDetailsState_0(
          this,
          Invocation.getter(#state),
        ),
        returnValueForMissingStub: _FakePersonDetailsState_0(
          this,
          Invocation.getter(#state),
        ),
      ) as _i2.PersonDetailsState);

  @override
  _i4.Stream<_i2.PersonDetailsState> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i4.Stream<_i2.PersonDetailsState>.empty(),
        returnValueForMissingStub: _i4.Stream<_i2.PersonDetailsState>.empty(),
      ) as _i4.Stream<_i2.PersonDetailsState>);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  void add(_i2.PersonDetailEvent? event) => super.noSuchMethod(
        Invocation.method(
          #add,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onEvent(_i2.PersonDetailEvent? event) => super.noSuchMethod(
        Invocation.method(
          #onEvent,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void emit(_i2.PersonDetailsState? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void on<E extends _i2.PersonDetailEvent>(
    _i5.EventHandler<E, _i2.PersonDetailsState>? handler, {
    _i5.EventTransformer<E>? transformer,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #on,
          [handler],
          {#transformer: transformer},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onTransition(
          _i5.Transition<_i2.PersonDetailEvent, _i2.PersonDetailsState>?
              transition) =>
      super.noSuchMethod(
        Invocation.method(
          #onTransition,
          [transition],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  void onChange(_i5.Change<_i2.PersonDetailsState>? change) =>
      super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [PersonRepositoryContract].
///
/// See the documentation for Mockito's code generation for more information.
class MockPersonRepositoryContract extends _i1.Mock
    implements _i6.PersonRepositoryContract {
  @override
  _i4.Future<_i3.Result<_i7.PersonEntity>> fetchPersonData(int? personId) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchPersonData,
          [personId],
        ),
        returnValue: _i4.Future<_i3.Result<_i7.PersonEntity>>.value(
            _FakeResult_1<_i7.PersonEntity>(
          this,
          Invocation.method(
            #fetchPersonData,
            [personId],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i3.Result<_i7.PersonEntity>>.value(
                _FakeResult_1<_i7.PersonEntity>(
          this,
          Invocation.method(
            #fetchPersonData,
            [personId],
          ),
        )),
      ) as _i4.Future<_i3.Result<_i7.PersonEntity>>);
}
