// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:film_flu/env/env.dart';
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return windows;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions web = FirebaseOptions(
    apiKey: Env.firebaseApiKeyWeb,
    appId: Env.firebaseAppIdWeb,
    messagingSenderId: Env.firebaseMessagingSenderId,
    projectId: Env.firebaseProjectName,
    authDomain: '${Env.firebaseProjectName}.firebaseapp.com',
    storageBucket: '${Env.firebaseProjectName}.firebasestorage.app',
    measurementId: Env.firebaseMeasurementId,
  );

  static FirebaseOptions android = FirebaseOptions(
    apiKey: Env.firebaseApiKeyAndroid,
    appId: Env.firebaseAppIdAndroid,
    messagingSenderId: Env.firebaseMessagingSenderId,
    projectId: Env.firebaseProjectName,
    storageBucket: '${Env.firebaseProjectName}.firebasestorage.app',
  );

  static FirebaseOptions windows = FirebaseOptions(
    apiKey: Env.firebaseApiKeyWeb,
    appId: Env.firebaseAppIdWeb,
    messagingSenderId: Env.firebaseMessagingSenderId,
    projectId: Env.firebaseProjectName,
    authDomain: '${Env.firebaseProjectName}.firebaseapp.com',
    storageBucket: '${Env.firebaseProjectName}.firebasestorage.app',
    measurementId: Env.firebaseMeasurementId,
  );

  static FirebaseOptions macos = FirebaseOptions(
    apiKey: Env.firebaseApiKeyApple,
    appId: Env.firebaseAppIdApple,
    messagingSenderId: Env.firebaseMessagingSenderId,
    projectId: Env.firebaseProjectName,
    storageBucket: '${Env.firebaseProjectName}.firebasestorage.app',
    iosClientId: Env.firebaseClientIdApple,
    iosBundleId: 'com.dherediat97.filmflu',
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: Env.firebaseApiKeyApple,
    appId: Env.firebaseAppIdApple,
    messagingSenderId: Env.firebaseMessagingSenderId,
    projectId: Env.firebaseProjectName,
    storageBucket: '${Env.firebaseProjectName}.firebasestorage.app',
    iosClientId: Env.firebaseClientIdApple,
    iosBundleId: 'com.dherediat97.filmflu',
  );
}
