name: Build App
on:
  workflow_call:
      inputs:
        environment:
          required: true
          type: string
        TMDB_API_KEY:
          required: true
          type: string
        FIREBASE_API_KEY_WEB:
          required: true
          type: string
        FIREBASE_API_KEY_ANDROID:
          required: true
          type: string
        FIREBASE_API_KEY_APPLE:
          required: true
          type: string
        FIREBASE_MESSAGING_SENDER_ID:
          required: true
          type: string
        FIREBASE_APP_ID_WEB:
          required: true
          type: string
        FIREBASE_APP_ID_ANDROID:
          required: true
          type: string
        FIREBASE_APP_ID_APPLE:
          required: true
          type: string
        FIREBASE_CLIENT_ID_APPLE:
          required: true
          type: string
        FIREBASE_PROJECT_NAME:
          required: true
          type: string
        FIREBASE_MEASUREMENT_ID:
          required: true
          type: string
        GOOGLE_CLIENT_ID:
          required: true
          type: string
defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
           channel: stable
           cache: true
      - run: flutter clean
      - run: flutter pub get
      - run: echo "TMDB_API_KEY=${{ inputs.TMDB_API_KEY }}" > .env
      - run: echo "FIREBASE_API_KEY_WEB=${{ inputs.FIREBASE_API_KEY_WEB }}" > .env
      - run: echo "FIREBASE_API_KEY_ANDROID=${{ inputs.FIREBASE_API_KEY_ANDROID }}" > .env
      - run: echo "FIREBASE_API_KEY_APPLE=${{ inputs.FIREBASE_API_KEY_APPLE }}" > .env
      - run: echo "FIREBASE_MESSAGING_SENDER_ID=${{ inputs.FIREBASE_MESSAGING_SENDER_ID }}" > .env
      - run: echo "FIREBASE_APP_ID_WEB=${{ inputs.FIREBASE_APP_ID_WEB }}" > .env
      - run: echo "FIREBASE_APP_ID_ANDROID=${{ inputs.FIREBASE_APP_ID_ANDROID }}" > .env
      - run: echo "FIREBASE_APP_ID_APPLE=${{ inputs.FIREBASE_APP_ID_APPLE }}" > .env
      - run: echo "FIREBASE_CLIENT_ID_APPLE=${{ inputs.FIREBASE_CLIENT_ID_APPLE }}" > .env
      - run: echo "FIREBASE_PROJECT_NAME=${{ inputs.FIREBASE_PROJECT_NAME }}" > .env
      - run: echo "FIREBASE_MEASUREMENT_ID=${{ inputs.FIREBASE_MEASUREMENT_ID}}" > .env
      - run: echo "GOOGLE_CLIENT_ID=${{ inputs.GOOGLE_CLIENT_ID }}" > .env
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_DEBUG: false
          envkey_TMDB_API_KEY: ${{ inputs.TMDB_API_KEY }}
          envkey_FIREBASE_API_KEY_WEB: ${{ inputs.FIREBASE_API_KEY_WEB }}
          envkey_FIREBASE_API_KEY_ANDROID: ${{ inputs.FIREBASE_API_KEY_ANDROID }}
          envkey_FIREBASE_API_KEY_APPLE: ${{ inputs.FIREBASE_API_KEY_APPLE }}
          envkey_FIREBASE_MESSAGING_SENDER_ID: ${{ inputs.FIREBASE_MESSAGING_SENDER_ID }}
          envkey_FIREBASE_APP_ID_WEB: ${{ inputs.FIREBASE_APP_ID_WEB}}
          envkey_FIREBASE_APP_ID_ANDROID: ${{ inputs.FIREBASE_APP_ID_ANDROID}}
          envkey_FIREBASE_APP_ID_APPLE: ${{ inputs.FIREBASE_APP_ID_APPLE}}
          envkey_FIREBASE_CLIENT_ID_APPLE: ${{ inputs.FIREBASE_CLIENT_ID_APPLE}}
          envkey_FIREBASE_MEASUREMENT_ID: ${{ inputs.FIREBASE_MEASUREMENT_ID}}
          envkey_FIREBASE_PROJECT_NAME: ${{ inputs.FIREBASE_PROJECT_NAME}}
          envkey_GOOGLE_CLIENT_ID: ${{ inputs.GOOGLE_CLIENT_ID}}
          file_name: .env
      - run: flutter pub run build_runner build --delete-conflicting-outputs
      - run: flutter gen-l10n