name: Build App
on:
    workflow_call:       
        outputs:
         reusable_output:
            description: 'Output from the reusable workflow'
            value: ${{ jobs.reusable-workflow-job.outputs.job_output }}
defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
           channel: stable
           cache: true
      - run: flutter clean
      - run: flutter pub get
      - run: echo "TMDB_API_KEY=${{ secrets.TMDB_API_KEY }}" > .env
      - run: echo "FIREBASE_API_KEY_WEB=${{ secrets.FIREBASE_API_KEY_WEB }}" > .env
      - run: echo "FIREBASE_API_KEY_ANDROID=${{ secrets.FIREBASE_API_KEY_ANDROID }}" > .env
      - run: echo "FIREBASE_API_KEY_APPLE=${{ secrets.FIREBASE_API_KEY_APPLE }}" > .env
      - run: echo "FIREBASE_MESSAGING_SENDER_ID=${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}" > .env
      - run: echo "FIREBASE_APP_ID_WEB=${{ secrets.FIREBASE_APP_ID_WEB }}" > .env
      - run: echo "FIREBASE_APP_ID_ANDROID=${{ secrets.FIREBASE_APP_ID_ANDROID }}" > .env
      - run: echo "FIREBASE_APP_ID_APPLE=${{ secrets.FIREBASE_APP_ID_APPLE }}" > .env
      - run: echo "FIREBASE_CLIENT_ID_APPLE=${{ secrets.FIREBASE_CLIENT_ID_APPLE }}" > .env
      - run: echo "FIREBASE_PROJECT_NAME=${{ secrets.FIREBASE_PROJECT_NAME }}" > .env
      - run: echo "FIREBASE_MEASUREMENT_ID=${{ secrets.FIREBASE_MEASUREMENT_ID}}" > .env
      - run: echo "GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}" > .env
      - run: flutter pub run build_runner build --delete-conflicting-outputs
      - run: flutter gen-l10n