name: Film Flu API

on:
  pull_request:
    branches: [api]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        node-version: [10]
        dart-version: [stable, dev]
        # for now, code-version will mirror dart-version to reduce number of bots
        # code-version: [stable] #, insiders]
        bot: [flutter_debug, flutter_debug_chrome, flutter_test_debug, dart_web_debug, flutter_repo, dart_debug, dart, flutter, misc]
        include:
          - dart-version: stable
            flutter-version: beta
            code-version: stable
          - dart-version: dev
            flutter-version: dev
            code-version: insiders
    steps:
      - uses: actions/checkout@v3
      - name: Setup Dart ${{ matrix.dart-version }}
        uses: DanTup/gh-actions/setup-dart@master
        with:
          channel: ${{ matrix.dart-version }}
      - run: dart format --output=none --set-exit-if-changed .
      - run: dart run ./lib/network/server_api.dart
