# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Film Flu Web App

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v1
        - uses: subosito/flutter-action@v2
          with:
            channel: 'stable' # or: 'beta', 'dev' or 'master'
        - run: flutter pub get
        - run: flutter config --enable-web
          env:
            TMDB_KEY: ${{ secrets.TMDB_KEY }}
        - run: dart run build_runner build
        - run: flutter build web
        - uses: bluefireteam/flutter-gh-pages@v7
          with:
            baseHref: /FilmFlu/
        - name: Archive Production Artifact
          uses: actions/upload-artifact@master
          with:
            name: platform
            path: build/web
