# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Film Flu Web

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v2
        - run: dart run build_runner build
        - name: Make envfile
          uses: SpicyPizza/create-envfile@v2.0
          with:
            file_name: .env
        - uses: subosito/flutter-action@v1
        - uses: bluefireteam/flutter-gh-pages@v7
          with:
            baseHref: /FilmFlu/
