# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Film Flu Android App

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-java@v2
          with:
            distribution: 'zulu'
            java-version: '11'
        - uses: subosito/flutter-action@v2
          with:
            channel: 'stable' # or: 'beta', 'dev' or 'master'
        - name: Write TMDB_KEY to .env
          run: echo 'TMDB_KEY={{ secrets.TMDB_KEY }}' > .env
        - run: flutter pub get
          env:
            TMDB_KEY: ${{ secrets.TMDB_KEY }} 
            IMAGE_BASE_URL: ${{ secrets.IMAGE_BASE_URL }}
            EXEC_ENV: 'github_actions'
        - run: flutter build apk
        - run: flutter build appbundle
        - name: Archive Production Artifact
          uses: actions/upload-artifact@master
          with:
            name: android app
            path: android/build