name: Film Flu Web App

on:
  push:
   branches: [ "main" ]
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v4
        - uses: subosito/flutter-action@v2
          with:
            channel: stable
            cache: true
            # optional parameters follow
            cache-key: "flutter-:os:-:channel:-:version:-:arch:-:hash:" # change this to force refresh cache
            cache-path: "${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:" # change this to specify the cache path
            pub-cache-key: "flutter-pub:os:-:channel:-:version:-:arch:-:hash:" # change this to force refresh cache of dart pub get dependencies
            pub-cache-path: "${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:" # change this to specify the cache path
        - run: flutter clean
        - run: flutter pub get
        - run: echo "TMDB_API_KEY=${{ secrets.TMDB_API_KEY }}" > .env
        - run: echo "FIREBASE_API_KEY_WEB=${{ secrets.FIREBASE_API_KEY_WEB }}" > .env
        - run: echo "FIREBASE_API_KEY_ANDROID=${{ secrets.FIREBASE_API_KEY_ANDROID }}" > .env
        - run: echo "FIREBASE_API_KEY_APPLE=${{ secrets.FIREBASE_API_KEY_APPLE }}" > .env
        - run: echo "FIREBASE_MESSAGING_SENDER_ID=${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}" > .env
        - run: echo "FIREBASE_APP_ID_WEB=${{ secrets.FIREBASE_APP_ID_WEB }}" > .env
        - run: echo "FIREBASE_APP_ID_ANDROID=${{ secrets.FIREBASE_APP_ID_ANDROID }}" > .env
        - run: echo "FIREBASE_APP_ID_APPLE=${{ secrets.FIREBASE_APP_ID_APPLE }}" > .env
        - run: echo "FIREBASE_CLIENT_ID_APPLE=${{ secrets.FIREBASE_CLIENT_ID_APPLE }}" > .env
        - run: echo "FIREBASE_PROJECT_NAME=${{ secrets.FIREBASE_PROJECT_NAME }}" > .env
        - run: echo "FIREBASE_MEASUREMENT_ID=${{ secrets.FIREBASE_MEASUREMENT_ID}}" > .env
        - run: echo "GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}" > .env
        - run: flutter pub run build_runner build --delete-conflicting-outputs
        - uses: bluefireteam/flutter-gh-pages@v9
          with:
            baseHref: /FilmFlu/
            targetBranch: gh-pages
