name: Film Flu Web App

on:
  push:
   branches: [ "main" ]
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - uses: ./.github/actions/setup-composite
          with:
            environment: "production"
            TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
            FIREBASE_API_KEY_WEB: ${{ secrets.FIREBASE_API_KEY_WEB }}
            FIREBASE_API_KEY_ANDROID: ${{ secrets.FIREBASE_API_KEY_ANDROID }}
            FIREBASE_API_KEY_APPLE: ${{ secrets.FIREBASE_API_KEY_APPLE }}
            FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
            FIREBASE_APP_ID_WEB: ${{ secrets.FIREBASE_APP_ID_WEB}}
            FIREBASE_APP_ID_ANDROID: ${{ secrets.FIREBASE_APP_ID_ANDROID}}
            FIREBASE_APP_ID_APPLE: ${{ secrets.FIREBASE_APP_ID_APPLE}}
            FIREBASE_CLIENT_ID_APPLE: ${{ secrets.FIREBASE_CLIENT_ID_APPLE}}
            FIREBASE_MEASUREMENT_ID: ${{ secrets.FIREBASE_MEASUREMENT_ID}}
            FIREBASE_PROJECT_NAME: ${{ secrets.FIREBASE_PROJECT_NAME}}
            GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID}}
        - uses: bluefireteam/flutter-gh-pages@v9
          with:
            baseHref: /FilmFlu/
            targetBranch: gh-pages
