name: Test Units FilmFlu

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    if: github.actor == 'dherediat97'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
            channel: 'stable'
      - run: flutter clean
      - run: flutter pub get
      - name: Write TMDB_KEY to .env
        run:
          set -o noclobber
          echo TMDB_KEY={{ secrets.TMDB_KEY }} >> .env
      - name: Create .env
        run: echo "TMDB_KEY=${{ secrets.TMDB_KEY }}" > .env
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_DEBUG: false
          envkey_TMDB_KEY: ${{ secrets.TMDB_KEY }}
          file_name: .env
      - run: flutter pub run build_runner build --delete-conflicting-outputs
      - run: flutter gen-l10n

      - name: Analyze project source
        run: flutter analyze

      - name: Run tests
        run: flutter test
