name: Test Units FilmFlu

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
            channel: 'stable'
      - run: flutter clean
      - run: flutter pub get
      - name: Build & compile classes
        run: flutter pub run build_runner build --delete-conflicting-outputs
      - run: flutter gen-l10n

      - name: Analyze project source
       run: flutter analyze

      - name: Run tests
        run: flutter test

      - name: Run coverage
        run: ./runCoverage.sh
